name: IgnoreChat
main: com.feildmaster.ignorechat.Ignore
version: ${project.version}
author: feildmaster
commands:
  ignore:
    description: Ignore a player
  ignore-list:
    description: List ignored players
permissions:
  ignore.use:
    default: true
  ignore.block:
    defualt: op