name: IgnoreChat
main: feildmaster.IgnoreChat.Ignore
version: 1.1
author: feildmaster
commands:
  ignore:
    description: Ignore a player
  ignore-list:
    description: List ignored players
permissions:
  ignore.use:
    default: true
  ignore.block:
    defualt: op